#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$ROOT/tests/assert.sh"
ui="$(cat "$ROOT/scripts/cyder_settings_ui.swift")"
app="$(cat "$ROOT/scripts/cyder_app_main.swift")"
assert_contains "$ui" "重新套用所有設定（疑難排解）" "advanced tab should expose force reapply checkbox"
assert_contains "$ui" "forceReapplyChanged" "force checkbox should mark settings dirty"
assert_contains "$ui" "let force = forceReapply.state == .on" "confirm should capture force checkbox"
assert_contains "$ui" "onCommit?(shouldStopAll, requiresPrefixApply, force)" "commit should propagate force state"
assert_contains "$app" "forceReapply: Bool" "app delegate should receive force state"
assert_contains "$app" "CYDER_FORCE_SETTINGS" "apply-settings launcher should receive force environment"
assert_contains "$app" "forceReapply ? [\"CYDER_FORCE_SETTINGS\": \"1\"]" "force state should set environment only when checked"
assert_contains "$ui" "private func retinaChanged()" "Retina toggle should have a dedicated DPI synchronization handler"
assert_contains "$ui" "let targetDPI = retina.state == .on ? 192 : 96" "global Retina toggle should suggest 192 or 96 DPI"
assert_contains "$ui" "private func executableRetinaChanged()" "per-game Retina toggle should have a dedicated DPI synchronization handler"
assert_contains "$ui" "let targetDPI = executableRetina.state == .on ? 192 : 96" "per-game Retina toggle should suggest 192 or 96 DPI"
assert_contains "$ui" "retina.action = #selector(retinaChanged)" "global Retina control should use the synchronization handler"
assert_contains "$ui" "executableRetina.action = #selector(executableRetinaChanged)" "per-game Retina control should use the synchronization handler"
echo "PASS test-cyder-force-settings-ui"
