#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$ROOT/tests/assert.sh"

TMP="$(mktemp -d "${TMPDIR:-/tmp}/cyder-pin-vcs.XXXXXX")"
trap 'rm -rf "$TMP"' EXIT

# --- DXVK: vcs_tag must become RELEASE-pinned configure_file ---
DXVK="$TMP/dxvk"
mkdir -p "$DXVK"
printf '1.10.3\n' >"$DXVK/RELEASE"
cat >"$DXVK/version.h.in" <<'EOF'
#pragma once
#define DXVK_VERSION "@VCS_TAG@"
EOF
cat >"$DXVK/meson.build" <<'EOF'
project('dxvk', ['c', 'cpp'], version : 'v1.10.3', meson_version : '>= 0.49')

dxvk_version = vcs_tag(
  command: ['git', 'describe', '--dirty=+'],
  input:  'version.h.in',
  output: 'version.h',
)
EOF

# Simulate monorepo pollution: parent tag must not win after pin.
git -C "$TMP" init -q
git -C "$TMP" config user.email "test@example.com"
git -C "$TMP" config user.name "test"
git -C "$TMP" add dxvk/meson.build
git -C "$TMP" commit -qm "seed"
git -C "$TMP" tag v0.7.0
assert_eq "$(git -C "$DXVK" describe --tags --always 2>/dev/null || true)" "v0.7.0" \
  "fixture: bare git describe from dxvk dir must see parent Cyder-like tag"

out="$(python3 "$ROOT/scripts/pin-dxvk-version.py" "$DXVK")"
assert_eq "$out" "v1.10.3" "pin-dxvk-version should print pure RELEASE version"
assert_contains "$(cat "$DXVK/meson.build")" "configure_file(" \
  "meson.build should use configure_file after pin"
assert_contains "$(cat "$DXVK/meson.build")" "_dxvk_version_conf.set('VCS_TAG', 'v1.10.3')" \
  "meson.build should embed v1.10.3 from RELEASE"
if grep -q 'vcs_tag' "$DXVK/meson.build"; then
  echo "ASSERT failed: vcs_tag must be removed" >&2
  exit 1
fi

out2="$(python3 "$ROOT/scripts/pin-dxvk-version.py" "$DXVK")"
assert_eq "$out2" "v1.10.3" "pin-dxvk-version must be idempotent"

# --- MoltenVK: gen script must not call git rev-parse ---
MVK="$TMP/moltenvk"
mkdir -p "$MVK/Scripts" "$MVK/MoltenVK/MoltenVK/API"
cat >"$MVK/Scripts/gen_moltenvk_rev_hdr.sh" <<'EOF'
#!/bin/bash
MVK_GIT_REV=$(git rev-parse HEAD)
MVK_HDR_FILE="${BUILT_PRODUCTS_DIR}/mvkGitRevDerived.h"
echo "// Auto-generated by MoltenVK" > "${MVK_HDR_FILE}"
echo "static const char* mvkRevString = \"${MVK_GIT_REV}\";" >> "${MVK_HDR_FILE}"
EOF
chmod +x "$MVK/Scripts/gen_moltenvk_rev_hdr.sh"
cat >"$MVK/MoltenVK/MoltenVK/API/mvk_private_api.h" <<'EOF'
#define MVK_VERSION_MAJOR   1
#define MVK_VERSION_MINOR   2
#define MVK_VERSION_PATCH   10
#define MVK_VERSION_STRING       (MVK_STRINGIFY(MVK_VERSION_MAJOR) "." MVK_STRINGIFY(MVK_VERSION_MINOR) "." MVK_STRINGIFY(MVK_VERSION_PATCH))
EOF

mvk_out="$(python3 "$ROOT/scripts/pin-moltenvk-git-rev.py" "$MVK")"
assert_eq "$mvk_out" "1.2.10" "pin-moltenvk should use pure MVK version"
script="$(cat "$MVK/Scripts/gen_moltenvk_rev_hdr.sh")"
assert_contains "$script" 'MVK_GIT_REV="1.2.10"' "gen script should hardcode 1.2.10"
if grep -E 'git[[:space:]]+rev-parse' "$MVK/Scripts/gen_moltenvk_rev_hdr.sh" >/dev/null; then
  echo "ASSERT failed: gen script must not call git rev-parse" >&2
  exit 1
fi

assert_contains "$(cat "$ROOT/scripts/build-dxvk.sh")" 'pin-dxvk-version.py' \
  "build-dxvk.sh must invoke pin-dxvk-version.py"
assert_contains "$(cat "$ROOT/scripts/build-graphics-stack.sh")" 'pin-moltenvk-git-rev.py' \
  "build-graphics-stack.sh must invoke pin-moltenvk-git-rev.py"

echo "PASS test-pin-lib-vcs-version"
